[package]
name = "hexpm"
version = "0.1.0"
authors = ["Louis Pilfold <louis@lpil.uk>"]
edition = "2018"

readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/gleam-lang/hexpm-rust"
description = "A Rust client for the Hex package manager"
keywords = ["erlang", "gleam", "elixir", "hex", "api-client"]
categories = ["api-bindings"]

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
